Posts
muzyk0/snapix pull request #78
Opened 2024-04-08 08:35 UTC by Julian871

2024-04-08 09:15 UTC, Julian871 commented on apps/storage/src/files/application/use-cases/get-files.handler.ts
> +    }
Исправил

2024-04-09 16:21 UTC, muzyk0 requested changes

2024-04-09 16:21 UTC, muzyk0 commented on apps/main/src/features/posts/application/use-cases/create-post.handler.ts
> +    return new CreatePostViewDto(
Вернуть на возврат объекта

2024-04-09 16:21 UTC, muzyk0 commented on apps/main/src/features/posts/application/use-cases/create-post.handler.ts
>    async execute(dto: CreatePostCommand): Promise<Partial<Post>> {
Promise<Partial<Post>> => Promise<Partial<CreatePostViewDto>>

2024-04-09 16:21 UTC, muzyk0 commented on apps/main/src/features/posts/application/dto/outputPostView.dto.ts
> +  constructor(
не нужен конструктор

2024-04-09 16:21 UTC, muzyk0 commented on apps/main/src/features/posts/application/interface/index.ts
> +    pageSize: number | undefined
объект, а не параметры

2024-04-09 16:21 UTC, muzyk0 commented on apps/main/src/features/posts/application/interface/index.ts
> +    pageSize: number | undefined
public abstract findManyByUserId: (id: number, {pageSize, cursor}: {pageSize?: number, cursor?: number})

2024-04-09 16:21 UTC, muzyk0 commented on apps/main/prisma/schema.prisma
> +  imageId   String[]
отдельная сущьность для изображений лучше подойдет чем array

2024-04-09 16:21 UTC, muzyk0 commented on apps/main/src/core/adapters/storage/storage-service.adapter.ts
> +          .send<UploadManyFilesOutputDto>({ cmd: 'get-files', type }, referenceIds)
UploadFilesOutputDto[]

2024-04-09 16:21 UTC, muzyk0 commented on apps/main/src/core/adapters/storage/storage-service.adapter.ts
> +  ): Promise<UploadManyFilesOutputDto> {
```Promise<UploadFilesOutputDto>```

2024-04-09 16:21 UTC, muzyk0 commented on apps/main/src/core/adapters/storage/user-files.facade.ts
> +  abstract getImages(referenceIds: string[]): Promise<UploadManyFilesOutputDto>
```Promise<UploadFilesOutputDto>```

2024-04-09 16:21 UTC, muzyk0 commented on apps/main/src/core/adapters/storage/user-files.facade.ts
> +  public async getImages(referenceIds: string[]): Promise<UploadManyFilesOutputDto> {
```Promise<UploadFilesOutputDto>```

2024-04-09 16:21 UTC, muzyk0 commented on apps/main/src/features/posts/application/use-cases/get-all-user-posts.handler.ts
> +export class GetAllUserPostsHandler implements ICommandHandler<GetAllUserPostsCommand> {
А зачем в одинаковых хендлера? GetAllPostsHandler тоже самое

2024-04-09 16:21 UTC, muzyk0 commented on apps/main/src/features/posts/application/posts.service.ts
> +  async mapImagesWithPosts(posts: Post[]) {
тут и получение файлов и маппинг. Название не правильное.

2024-04-09 16:21 UTC, muzyk0 commented on apps/main/src/features/posts/application/posts.service.ts
> +      if (imageObjects.length > 0) {
if не нужен

2024-04-09 16:21 UTC, muzyk0 commented on apps/main/src/features/posts/application/posts.service.ts
> +          photos: [],
images: imageObjects.length > 0 ? imageObjects : []

2024-04-09 16:21 UTC, muzyk0 commented on apps/main/src/features/posts/controllers/dto/query.dto.ts
> +export class QueryDto {
Что такое query dto? Название слишком общее и не несет никакой информативности

2024-04-09 16:21 UTC, muzyk0 commented on apps/main/src/features/posts/controllers/open-api/get-all-user-posts.swagger.ts
> +          photos: {
images

2024-04-09 16:21 UTC, muzyk0 commented on apps/main/src/features/posts/controllers/dto/query.dto.ts
> +  @Transform((params: TransformFnParams) => parseInt(params.value))
parseInt(undefind) вернет NaN
@Type(() => Number)
@IsInt()

2024-04-09 16:21 UTC, muzyk0 commented on apps/main/src/features/posts/controllers/dto/query.dto.ts
> +export class QueryDto {
И вынести в общую папку т.к. будет использоваться везде

2024-04-09 16:21 UTC, muzyk0 commented on apps/main/src/features/posts/controllers/open-api/get-all-user-posts.swagger.ts
> +    ApiQuery({ name: 'pageSize', description: 'Page size', type: 'number' }),
Вынести в отдьельный декоратор т.к. будет использоваться везде

2024-04-09 16:21 UTC, muzyk0 commented on apps/main/src/features/posts/controllers/posts.controller.ts
> +  async getAllPosts(@Query('cursor') cursor: number, @Query('pageSize') pageSize: number) {
@Query() {cursor, pageSize}: QueryDto

2024-04-09 16:21 UTC, muzyk0 commented on apps/storage/src/files/application/use-cases/get-files.handler.ts
> +    return {
return filterFiles

2024-04-09 16:21 UTC, muzyk0 commented on apps/storage/src/files/application/use-cases/get-files.handler.ts
> +  async execute({ referenceIds }: GetFilesQuery): Promise<UploadManyFilesOutputDto | null> {
```async execute({ referenceIds }: GetFilesQuery): Promise<UploadManyFilesOutputDto[] | null> {```

2024-04-09 16:21 UTC, muzyk0 commented on libs/core/src/types/dto/upload-files.dto.ts
> +export class UploadManyFilesOutputDto {
Удалить

2025-12-08 21:05 UTC, merged